######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 16 12:00:09 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += ../libc64fc/libc64fc.a
LIBS += `libusb-config --libs`


# Input
HEADERS += GUI.h
FORMS += SIDPlay.ui
SOURCES += main.cpp GUI.cpp PSID.cpp
